name: my ci exp

on:
 push:
    branches: ["main","master"]
 workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Run a one-line script 
       run: echo hello world

      - name: Run a multi-line script
       run :
        echo iam manikanta 
        echo iam from hyderabad 


